#!/bin/python
import os
def ytdl():
    os.chdir("/sdcard/Download")
    import pafy
    while True:
        url  =  input("Copy the url from youtube here, "  + "To QUIT PRESS [q] ")
        if url == "q":
            quit()
        video  = pafy.new(url)
        resolution =  video.getbestaudio()
        try:
            resolution.download()
            print("{} Downloaded to {}".format(video.title, os.getcwd()))
            #time.sleep(4)
        except Exception as e:
            print(e)
        #time.sleep(2)
        for i in os.listdir():
            if i == video.title + ".webm":
                cnvrt = "mp3"
                print("Converting {} to {}".format(i, i[:-4] + cnvrt))
                
                try:
                    os.system("ffmpeg -i '"+ video.title +".webm' '"+video.title+".mp3' ")
                    print("File has been successfully converted")
                except:
                    print(i[:-4] + " already exists")
        for i in os.listdir():
            if i == video.title+".webm":
                os.remove(i)

ytdl()
